package domain

type BalanceSheet struct {
	Datekey                        string
	FiscalYear                     string
	FiscalQuarter                  string
	Cashneq                        float64
	Investmentsc                   float64
	Totalcash                      float64
	CashGrowth                     float64
	AccountsReceivable             float64
	OtherReceivables               float64
	Receivables                    float64
	Inventory                      float64
	RestrictedCash                 float64
	Othercurrent                   float64
	Assetsc                        float64
	NetPPE                         float64
	Investmentsnc                  float64
	Goodwill                       float64
	OtherIntangibles               float64
	Othernoncurrent                float64
	Assets                         float64
	AccountsPayable                float64
	AccruedExpenses                float64
	Debtc                          float64
	CurrentPortDebt                float64
	CurrentCapLeases               float64
	CurrentIncomeTaxesPayable      float64
	CurrentUnearnedRevenue         float64
	OtherCurrentLiabilities        float64
	CurrentLiabilities             float64
	Debtnc                         float64
	CapitalLeases                  float64
	LongTermUnearnedRevenue        float64
	LongTermDeferredTaxLiabilities float64
	Otherliabilitiesnoncurrent     float64
	Liabilities                    float64
	CommonStock                    float64
	Retearn                        float64
	OtherEquity                    float64
	Equity                         float64
	Liabilitiesequity              float64
	SharesOutFilingDate            float64
	SharesOutTotalCommon           float64
	Bvps                           float64
	TangibleBookValue              float64
	TangibleBookValuePerShare      float64
	Debt                           float64
	Netcash                        float64
	NetCashGrowth                  float64
	Netcashpershare                float64
	Workingcapital                 float64
	Land                           float64
	Machinery                      float64
	LeaseholdImprovements          float64
	TradingAssetSecurities         float64
}

type CashFlow struct {
	Datekey                  string
	FiscalYear               string
	FiscalQuarter            string
	NetIncomeCF              float64
	TotalDepAmorCF           float64
	Sbcomp                   float64
	ChangeAR                 float64
	ChangeInventory          float64
	ChangeAP                 float64
	ChangeUnearnedRev        float64
	ChangeOtherNetOperAssets float64
	OtherOperating           float64
	Ncfo                     float64
	OcfGrowth                float64
	Capex                    float64
	CashAcquisition          float64
	SalePurchaseIntangibles  float64
	InvestInSecurities       float64
	OtherInvesting           float64
	Ncfi                     float64
	DebtIssuedShortTerm      float64
	DebtIssuedLongTerm       float64
	DebtIssuedTotal          float64
	DebtRepaidShortTerm      float64
	DebtRepaidLongTerm       float64
	DebtRepaidTotal          float64
	NetDebtIssued            float64
	CommonIssued             float64
	CommonRepurchased        float64
	CommonDividendCF         float64
	OtherFinancing           float64
	Ncff                     float64
	Ncf                      float64
	Fcf                      float64
	FcfGrowth                float64
	FcfMargin                float64
	Fcfps                    float64
	LeveredFCF               float64
	UnleveredFCF             float64
	CashInterestPaid         float64
	CashTaxesPaid            float64
	ChangeNetWorkingCapital  float64
}

type IncomeStatement struct {
	Datekey           string
	FiscalYear        string
	FiscalQuarter     string
	Revenue           float64
	RevenueGrowth     float64
	Cor               float64
	Gp                float64
	Sgna              float64
	Rnd               float64
	Opex              float64
	Opinc             float64
	InterestExpense   float64
	InterestIncome    float64
	CurrencyGains     float64
	OtherNonOperating float64
	EbtExcl           float64
	GainInvestments   float64
	Pretax            float64
	Taxexp            float64
	Netinc            float64
	Netinccmn         float64
	NetIncomeGrowth   float64
	SharesBasic       float64
	SharesDiluted     float64
	SharesYoY         float64
	EpsBasic          float64
	EpsDil            float64
	EpsGrowth         float64
	Fcf               float64
	Fcfps             float64
	Dps               float64
	DividendGrowth    float64
	GrossMargin       float64
	OperatingMargin   float64
	ProfitMargin      float64
	FcfMargin         float64
	Taxrate           float64
	Ebitda            float64
	DepAmorEbitda     float64
	EbitdaMargin      float64
	Ebit              float64
	EbitMargin        float64
	RevenueAsReported float64
	PayoutRatio       float64
}

type FinancialRatios struct {
	Datekey           string
	FiscalYear        string
	FiscalQuarter     string
	Marketcap         float64
	MarketCapGrowth   float64
	Ev                float64
	LastCloseRatios   float64
	Pe                float64
	Ps                float64
	Pb                float64
	Pfcf              float64
	Pocf              float64
	EvRevenue         float64
	EvEbitda          float64
	EvEbit            float64
	EvFcf             float64
	DebtEquity        float64
	DebtEbitda        float64
	DebtFcf           float64
	AssetTurnover     float64
	InventoryTurnover float64
	QuickRatio        float64
	CurrentRatio      float64
	Roe               float64
	Roa               float64
	Roic              float64
	EarningsYield     float64
	FcfYield          float64
	DividendYield     float64
	PayoutRatio       float64
	BuybackYield      float64
	TotalReturn       float64
}
